# Generated by Django 5.1.7 on 2025-09-10 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('max_score', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_avg', models.FloatField(default=0)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
            ],
        ),
        migrations.AddField(
            model_name='co',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course'),
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.po')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('attainment_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.student')),
            ],
        ),
        migrations.CreateModel(
            name='COAggregateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained_marks', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
            ],
            options={
                'unique_together': {('course', 'co')},
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.po')),
            ],
            options={
                'unique_together': {('course', 'po')},
            },
        ),
        migrations.CreateModel(
            name='StudentTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained', models.FloatField(default=0)),
                ('total_max', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
