# Generated by Django 5.1.7 on 2026-01-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coattainment',
            name='attainment_percentage',
        ),
        migrations.AddField(
            model_name='coattainment',
            name='level_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='attainment_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
        migrations.CreateModel(
            name='COAggregateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained_marks', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
            ],
            options={
                'unique_together': {('course', 'co')},
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.po')),
            ],
            options={
                'unique_together': {('course', 'po')},
            },
        ),
        migrations.CreateModel(
            name='StudentTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained', models.FloatField(default=0)),
                ('total_max', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
