services:
  - type: web
    name: copo-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn copos.wsgi:application
    autoDeploy: true
    branch: main
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: copos.settings
